# Generated by Django 3.1.1 on 2020-10-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testgateway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100)),
            ],
        ),
    ]
