# Generated by Django 3.1.1 on 2020-10-28 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testgateway', '0002_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='testgateway.tests'),
        ),
    ]
