# Generated by Django 3.1.1 on 2020-11-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testgateway', '0006_auto_20201111_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userStat',
            field=models.ManyToManyField(blank=True, through='testgateway.Userstats', to='testgateway.Questions'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
