# Generated by Django 3.1.1 on 2020-11-13 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testgateway', '0007_auto_20201111_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
